In [9]:
%%time

import numpy as np
import pandas as pd

# Model parameters
S1_0 = 26
S2_0 = 29
sigma1 = 0.31
sigma2 = 0.21
rho = 0.3
r = 0.025
T = 0.5  # Six months
K = 50

np.random.seed(42)  # Set seed for reproducibility

# Simulation parameters
m = 150  # Time steps

res = pd.DataFrame(columns=['n', 'm', 'Option Value'])

for l in range(10):
    n = 50 * 2**l  # Number of paths
    N = 2 * n * m  # Number of samples

    option_values = np.zeros(n)

    # Discretize time
    delta_t = T / m

    # Monte Carlo simulation
    for k in range(n):
        S1 = S1_0
        S2 = S2_0
        max_value = 0

        z_samples = np.random.normal(0, 1, size=(2*m,))
        for j in range(m):
            z1 = z_samples[(2 * j)]
            z2 = z_samples[(2 * j + 1)]

            S1 *= np.exp((r - 0.5 * sigma1**2) * delta_t + sigma1 * np.sqrt(delta_t) * z1)
            S2 *= np.exp((r - 0.5 * sigma2**2) * delta_t + sigma2 * np.sqrt(delta_t) * (rho * z1 + np.sqrt(1 - rho**2) * z2))

            max_value = max(max_value, S1 + S2)

        option_values[k] = max(max_value - K, 0)

    # Calculate the Monte Carlo estimate of the option value
    option_value_estimate = option_values.mean()
    print(option_value_estimate)
    res.loc[l] = [n, m, option_value_estimate]

res.to_csv('hw2-q3.csv', index=False)
res

11.93651230116225
11.893098367057684
12.128893492583943
11.883443800423576
11.502191405964394
11.68409357764376
11.565590486796086
11.72714365884417

KeyboardInterrupt:

In [11]:
%%time

import numpy as np
import pandas as pd

# Model parameters
S1_0 = 26
S2_0 = 29
sigma1 = 0.31
sigma2 = 0.21
rho = 0.3
r = 0.025
T = 0.5  # Six months
K = 50

np.random.seed(42)  # Set seed for reproducibility

# Simulation parameters
m = 150  # Time steps

res = pd.DataFrame(columns=['n', 'm', 'Option Value'])

for l in range(10):
    n = 50 * 2**l  # Number of paths
    N = 2 * 2**l * 7500  # Number of samples

    option_values = np.zeros(n)

    # Discretize time
    delta_t = T / m

    z_samples = np.random.normal(0, 1, size=(N,))

    # Monte Carlo simulation
    for k in range(n):
        S1 = S1_0
        S2 = S2_0
        max_value = 0

        for j in range(m):
            z1 = np.random.normal(0, 1, size=(1,))
            z2 = np.random.normal(0, 1, size=(1,))

            S1 *= np.exp((r - 0.5 * sigma1**2) * delta_t + sigma1 * np.sqrt(delta_t) * z1)
            S2 *= np.exp((r - 0.5 * sigma2**2) * delta_t + sigma2 * np.sqrt(delta_t) * (rho * z1 + np.sqrt(1 - rho**2) * z2))

            max_value = max(max_value, S1 + S2)

        option_values[k] = max(max_value - K, 0)

    # Calculate the Monte Carlo estimate of the option value
    option_value_estimate = option_values.mean()
    print(option_value_estimate)
    res.loc[l] = [n, m, option_value_estimate]

res.to_csv('hw2-q3.csv', index=False)
res

11.492992600232785
12.475171243154866
11.631406967533199
11.677970013843664
11.777858916987874
11.810070947585146
11.687782188671406
11.679450545625421
11.793294599912755
11.714688086807403
Wall time: 2min 36s

         n      m  Option Value
0     50.0  150.0     11.492993
1    100.0  150.0     12.475171
2    200.0  150.0     11.631407
3    400.0  150.0     11.677970
4    800.0  150.0     11.777859
5   1600.0  150.0     11.810071
6   3200.0  150.0     11.687782
7   6400.0  150.0     11.679451
8  12800.0  150.0     11.793295
9  25600.0  150.0     11.714688